### ISSUE TITLE
AttributeError: 'PurePosixPath' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by bertainsikt** [sjacks26/FlockWatch#10]
Hi, 
I'm trying to use FlockWatch, I've followed all the set up instructions and when trying to run Flockwatch (python3 FlockWatch.py -n file) I get this error:
AttributeError: 'PurePosixPath' object has no attribute 'startswith'
Please, could you help me? I don't know how to deal with this error?
Thanks in advance
Berta

**Comment by bertainsikt** [comment]
Hi again,
The complete error message is this:
Traceback (most recent call last):
  File "FlockWatch.py", line 36, in <module>
    logging.basicConfig(filename=log_file_name,filemode='a+',level=logging.DEBUG, format="[%(asctime)s] %(levelname)s:%(name)s:%(message)s")
  File "/usr/lib/python3.5/logging/__init__.py", line 1744, in basicConfig
    h = FileHandler(filename, mode)
  File "/usr/lib/python3.5/logging/__init__.py", line 998, in __init__
    self.baseFilename = os.path.abspath(filename)
  File "/usr/lib/python3.5/posixpath.py", line 357, in abspath
    if not isabs(path):
  File "/usr/lib/python3.5/posixpath.py", line 64, in isabs
    return s.startswith(sep)
AttributeError: 'PurePosixPath' object has no attribute 'startswith'

Apparently the error comes from logging package, but I don't understand which is the problem, the package is installed and updated.

**Comment by sjacks26** [comment]
Seems like this might be a problem with python3.5. Can be fixed by converting the log_file_name object from a PurePath object into a string.

I pushed an update (https://github.com/sjacks26/FlockWatch/commit/47c8b316734b20f0e8f267f50814ade3691120e6) that should solve this problem. Can you see if you still run into this problem with the new code?
